# Generated by Django 5.2.8 on 2025-11-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UzmanlikAlani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Uzmanlık Alanları',
            },
        ),
        migrations.CreateModel(
            name='Avukat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('unvan', models.CharField(help_text='Örn: Kurucu Avukat, Avukat', max_length=100)),
                ('biyografi', models.TextField()),
                ('fotograf', models.ImageField(blank=True, null=True, upload_to='avukat_fotolari/')),
                ('uzmanlik_alanlari', models.ManyToManyField(related_name='avukatlar', to='ana_sayfa.uzmanlikalani')),
            ],
            options={
                'verbose_name_plural': 'Avukatlar',
            },
        ),
    ]
