# Generated by Django 5.2.8 on 2025-11-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_sayfa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iletisim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('eposta', models.EmailField(max_length=254)),
                ('konu', models.CharField(max_length=150)),
                ('mesaj', models.TextField()),
                ('gonderme_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'İletişim Mesajları',
            },
        ),
    ]
