# Generated by Django 5.2.8 on 2025-11-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_sayfa', '0002_iletisim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Haber/Karar Başlığı')),
                ('ozet', models.TextField(verbose_name='Kısa Özet')),
                ('icerik', models.TextField(verbose_name='Haber İçeriği / Karar Metni')),
                ('yayin_tarihi', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL Adresi')),
            ],
            options={
                'verbose_name_plural': 'Haberler ve Kararlar',
                'ordering': ['-yayin_tarihi'],
            },
        ),
    ]
