# Generated by Django 5.2.8 on 2025-11-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_sayfa', '0003_haber'),
    ]

    operations = [
        migrations.AddField(
            model_name='avukat',
            name='biyografi_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='avukat',
            name='biyografi_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='avukat',
            name='unvan_en',
            field=models.CharField(help_text='Örn: Kurucu Avukat, Avukat', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avukat',
            name='unvan_tr',
            field=models.CharField(help_text='Örn: Kurucu Avukat, Avukat', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='haber',
            name='baslik_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Haber/Karar Başlığı'),
        ),
        migrations.AddField(
            model_name='haber',
            name='baslik_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Haber/Karar Başlığı'),
        ),
        migrations.AddField(
            model_name='haber',
            name='icerik_en',
            field=models.TextField(null=True, verbose_name='Haber İçeriği / Karar Metni'),
        ),
        migrations.AddField(
            model_name='haber',
            name='icerik_tr',
            field=models.TextField(null=True, verbose_name='Haber İçeriği / Karar Metni'),
        ),
        migrations.AddField(
            model_name='haber',
            name='ozet_en',
            field=models.TextField(null=True, verbose_name='Kısa Özet'),
        ),
        migrations.AddField(
            model_name='haber',
            name='ozet_tr',
            field=models.TextField(null=True, verbose_name='Kısa Özet'),
        ),
    ]
